
using System.Collections.Generic;
using HendecamMod.Content.Items.Accessories.NastyPatty;
using HendecamMod.Content.Items.Accessories.PeaceAmongNations;
using HendecamMod.Content.Items.Accessories.Rampart;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;
using static HendecamMod.Content.Items.Accessories.NastyPatty.NastyPattyAccessory;

namespace HendecamMod.Content.Items.Accessories.NormalOnes
    {
    //[AutoloadEquip(EquipType.Beard)]
    public class SoulOfImmunityAccessory : ModItem
        {
        public override void SetDefaults()
            {
            Item.width = 32;
            Item.height = 32;
            Item.value = Item.sellPrice(silver: 64000);
            Item.rare = ItemRarityID.Expert;
            Item.accessory = true;

            }
        public override void ModifyTooltips(List<TooltipLine> tooltips)
            {
            tooltips.Add(new TooltipLine(Mod, "Tooltip#1", "Grants 200 Health, 30% increased attack speed, double the breath timer, Hellfire for all attacks,"));
            tooltips.Add(new TooltipLine(Mod, "Tooltip#1", "50 mana, 4 Luck, 30% Damage Reduction, 35 Safe Fall Distance, 3hp/s, Light, 25% Crit Chance,"));
            tooltips.Add(new TooltipLine(Mod, "Tooltip#1", "50 Defense, Doubled Armor Penetraton, 50% more Generic Damage, MUCH higher jump speed, Flight, Liquid walking,"));
            tooltips.Add(new TooltipLine(Mod, "Tooltip#1", "Super fast movement, More mobility on ice, Faster running speed on sand, 30 fishing power, and Auto jump"));
            tooltips.Add(new TooltipLine(Mod, "Tooltip#1", "Immune to every buff, debuff, knockback, fall damage, fire blocks, and liquids"));
            tooltips.Add(new TooltipLine(Mod, "Tooltip#1", "Every enemy should be friendly"));
            }
        public override void UpdateEquip(Player player)
            {
            player.CancelAllBootRunVisualEffects();
            player.hellfireTreads = true;
            if (!player.mount.Active || player.mount.Type != MountID.WallOfFleshGoat)
                {
                player.DoBootsEffect(player.DoBootsEffect_PlaceFlamesOnTile);
                player.DoBootsEffect(player.DoBootsEffect_PlaceFlamesOnTile);
                }
            player.GetModPlayer<NastyRegen>().NastyEffect = true;
            player.GetModPlayer<NastyLight>().NastyEffect = true;
            player.GetModPlayer<NastyCrit>().NastyEffect = true;
            player.GetModPlayer<NastyMovement>().NastyEffect = true;
            player.GetModPlayer<NastyPenetration>().NastyEffect = true;
            player.GetModPlayer<NastyDefense>().NastyEffect = true;
            player.GetModPlayer<NastyDamage>().NastyEffect = true;
            player.GetModPlayer<NastyJump>().NastyEffect = true;
            player.GetModPlayer<NastyBreath>().NastyEffect = true;
            player.GetModPlayer<NastySpeed>().NastyEffect = true;
            player.GetModPlayer<NastyHealth>().NastyEffect = true;
            player.GetModPlayer<NastyFire>().NastyEffect = true;
            player.GetModPlayer<NastyLuck>().NastyEffect = true;
            player.GetModPlayer<NastyMana>().NastyEffect = true;
            player.GetModPlayer<NastyEndurance>().NastyEffect = true;
            player.GetModPlayer<NastyFall>().NastyEffect = true;
            player.breathEffectiveness += 200000f;
            player.fishingSkill += 30;
            player.rocketBoots = 2;
            player.vanityRocketBoots = 5;
            player.moveSpeed += 1f;
            player.accRunSpeed = 12f;
            player.autoJump = true;
            player.jumpSpeedBoost += 0.6f;
            player.extraFall += 10;
            player.ignoreWater = true;
            player.lavaImmune = true;
            player.iceSkate = true;
            player.waterWalk2 = true;
            player.lavaRose = true;
            player.desertBoots = true;
            player.noFallDmg = true;
            player.flowerBoots = true;
            player.npcTypeNoAggro[NPCID.Raven] = true;
            player.npcTypeNoAggro[NPCID.HoppinJack] = true;
            player.buffImmune[BuffID.WeaponImbueConfetti] = true;
            player.buffImmune[BuffID.WeaponImbueCursedFlames] = true;
            player.buffImmune[BuffID.WeaponImbueFire] = true;
            player.buffImmune[BuffID.WeaponImbueGold] = true;
            player.buffImmune[BuffID.WeaponImbueIchor] = true;
            player.buffImmune[BuffID.WeaponImbueNanites] = true;
            player.buffImmune[BuffID.WeaponImbuePoison] = true;
            player.buffImmune[BuffID.WeaponImbueVenom] = true;
            player.buffImmune[BuffID.AmmoReservation] = true;
            player.buffImmune[BuffID.Archery] = true;
            player.buffImmune[BuffID.Endurance] = true;
            player.buffImmune[BuffID.Heartreach] = true;
            player.buffImmune[BuffID.Inferno] = true;
            player.buffImmune[BuffID.Calm] = true;
            player.buffImmune[BuffID.Battle] = true;
            player.buffImmune[BuffID.Ironskin] = true;
            player.buffImmune[BuffID.Lifeforce] = true;
            player.buffImmune[BuffID.MagicPower] = true;
            player.buffImmune[BuffID.ManaRegeneration] = true;
            player.buffImmune[BuffID.Rage] = true;
            player.buffImmune[BuffID.Summoning] = true;
            player.buffImmune[BuffID.Thorns] = true;
            player.buffImmune[BuffID.Titan] = true;
            player.buffImmune[BuffID.Warmth] = true;
            player.buffImmune[BuffID.Wrath] = true;
            player.buffImmune[BuffID.Regeneration] = true;
            player.buffImmune[BuffID.Hunter] = true;
            player.buffImmune[BuffID.AmmoBox] = true;
            player.buffImmune[BuffID.Bewitched] = true;
            player.buffImmune[BuffID.Clairvoyance] = true;
            player.buffImmune[BuffID.Sharpened] = true;
            player.buffImmune[BuffID.WarTable] = true;
            player.buffImmune[BuffID.SugarRush] = true;
            player.buffImmune[BuffID.Campfire] = true;
            player.buffImmune[BuffID.DryadsWard] = true;
            player.buffImmune[BuffID.Sunflower] = true;
            player.buffImmune[BuffID.HeartLamp] = true;
            player.buffImmune[BuffID.Honey] = true;
            player.buffImmune[BuffID.PeaceCandle] = true;
            player.buffImmune[BuffID.StarInBottle] = true;
            player.buffImmune[BuffID.CatBast] = true;
            player.buffImmune[BuffID.MonsterBanner] = true;
            player.buffImmune[BuffID.Crate] = true;
            player.buffImmune[BuffID.Fishing] = true;
            player.buffImmune[BuffID.Sonar] = true;
            player.buffImmune[BuffID.Lucky] = true;
            player.buffImmune[BuffID.Builder] = true;
            player.buffImmune[BuffID.BiomeSight] = true;
            player.buffImmune[BuffID.Invisibility] = true;
            player.buffImmune[BuffID.Featherfall] = true;
            player.buffImmune[BuffID.Flipper] = true;
            player.buffImmune[BuffID.Gills] = true;
            player.buffImmune[BuffID.Mining] = true;
            player.buffImmune[BuffID.NightOwl] = true;
            player.buffImmune[BuffID.ObsidianSkin] = true;
            player.buffImmune[BuffID.Shine] = true;
            player.buffImmune[BuffID.Spelunker] = true;
            player.buffImmune[BuffID.Swiftness] = true;
            player.buffImmune[BuffID.Dangersense] = true;
            player.buffImmune[BuffID.WaterWalking] = true;
            player.buffImmune[BuffID.Gravitation] = true;
            player.buffImmune[BuffID.WellFed] = true;
            player.buffImmune[BuffID.WellFed2] = true;
            player.buffImmune[BuffID.WellFed3] = true;
            player.ClearBuff(BuffID.Flamingo);
            player.ClearBuff(BuffID.Rudolph);
            player.ClearBuff(BuffID.WitchBroom);
            player.ClearBuff(BuffID.BabyBird);
            player.ClearBuff(BuffID.BabySlime);
            player.ClearBuff(BuffID.DeadlySphere);
            player.ClearBuff(BuffID.StormTiger);
            player.ClearBuff(BuffID.Smolstar);
            player.ClearBuff(BuffID.FlinxMinion);
            player.ClearBuff(BuffID.HornetMinion);
            player.ClearBuff(BuffID.ImpMinion);
            player.ClearBuff(BuffID.PirateMinion);
            player.ClearBuff(BuffID.Pygmies);
            player.ClearBuff(BuffID.Ravens);
            player.ClearBuff(BuffID.BatOfLight);
            player.ClearBuff(BuffID.SharknadoMinion);
            player.ClearBuff(BuffID.SpiderMinion);
            player.ClearBuff(BuffID.StardustMinion);
            player.ClearBuff(BuffID.StardustDragonMinion);
            player.ClearBuff(BuffID.EmpressBlade);
            player.ClearBuff(BuffID.TwinEyesMinion);
            player.ClearBuff(BuffID.UFOMinion);
            player.ClearBuff(BuffID.VampireFrog);
            player.ClearBuff(BuffID.BasiliskMount);
            player.ClearBuff(BuffID.BeeMount);
            player.ClearBuff(BuffID.BunnyMount);
            player.ClearBuff(BuffID.CuteFishronMount);
            player.ClearBuff(BuffID.DarkHorseMount);
            player.ClearBuff(BuffID.DarkMageBookMount);
            player.ClearBuff(BuffID.DrillMount);
            player.ClearBuff(BuffID.GolfCartMount);
            player.ClearBuff(BuffID.LavaSharkMount);
            player.ClearBuff(BuffID.MajesticHorseMount);
            player.ClearBuff(BuffID.PaintedHorseMount);
            player.ClearBuff(BuffID.PigronMount);
            player.ClearBuff(BuffID.PirateShipMount);
            player.ClearBuff(BuffID.PogoStickMount);
            player.ClearBuff(BuffID.QueenSlimeMount);
            player.ClearBuff(BuffID.SantankMount);
            player.ClearBuff(BuffID.ScutlixMount);
            player.ClearBuff(BuffID.SlimeMount);
            player.ClearBuff(BuffID.SpookyWoodMount);
            player.ClearBuff(BuffID.TurtleMount);
            player.ClearBuff(BuffID.UFOMount);
            player.ClearBuff(BuffID.UnicornMount);
            player.ClearBuff(BuffID.WallOfFleshGoatMount);
            player.ClearBuff(BuffID.WolfMount);
            player.ClearBuff(BuffID.CrimsonHeart);
            player.ClearBuff(BuffID.FairyBlue);
            player.ClearBuff(BuffID.FairyGreen);
            player.ClearBuff(BuffID.FairyRed);
            player.ClearBuff(BuffID.FairyQueenPet);
            player.ClearBuff(BuffID.PetDD2Ghost);
            player.ClearBuff(BuffID.PumpkingPet);
            player.ClearBuff(BuffID.MagicLantern);
            player.ClearBuff(BuffID.ShadowOrb);
            player.ClearBuff(BuffID.SuspiciousTentacle);
            player.ClearBuff(BuffID.GolemPet);
            player.ClearBuff(BuffID.Wisp);
            player.ClearBuff(BuffID.PetBunny);
            player.ClearBuff(BuffID.PetDD2Dragon);
            player.ClearBuff(BuffID.PetDD2Gato);
            player.ClearBuff(BuffID.PetLizard);
            player.ClearBuff(BuffID.PetParrot);
            player.ClearBuff(BuffID.PetSapling);
            player.ClearBuff(BuffID.PetSpider);
            player.ClearBuff(BuffID.PetTurtle);
            player.ClearBuff(BuffID.BerniePet);
            player.ClearBuff(BuffID.BlueChickenPet);
            player.ClearBuff(BuffID.BrainOfCthulhuPet);
            player.ClearBuff(BuffID.ChesterPet);
            player.ClearBuff(BuffID.DD2BetsyPet);
            player.ClearBuff(BuffID.DD2OgrePet);
            player.ClearBuff(BuffID.DeerclopsPet);
            player.ClearBuff(BuffID.DestroyerPet);
            player.ClearBuff(BuffID.DualSlimePet);
            player.ClearBuff(BuffID.DukeFishronPet);
            player.ClearBuff(BuffID.EaterOfWorldsPet);
            player.ClearBuff(BuffID.EverscreamPet);
            player.ClearBuff(BuffID.EyeOfCthulhuPet);
            player.ClearBuff(BuffID.GlommerPet);
            player.ClearBuff(BuffID.IceQueenPet);
            player.ClearBuff(BuffID.JunimoPet);
            player.ClearBuff(BuffID.KingSlimePet);
            player.ClearBuff(BuffID.LunaticCultistPet);
            player.ClearBuff(BuffID.MartianPet);
            player.ClearBuff(BuffID.MoonLordPet);
            player.ClearBuff(BuffID.PigPet);
            player.ClearBuff(BuffID.PlanteraPet);
            player.ClearBuff(BuffID.QueenSlimePet);
            player.ClearBuff(BuffID.SkeletronPet);
            player.ClearBuff(BuffID.SkeletronPrimePet);
            player.ClearBuff(BuffID.TwinsPet);
            player.ClearBuff(BuffID.BabyDinosaur);
            player.ClearBuff(BuffID.BabyEater);
            player.ClearBuff(BuffID.BabyGrinch);
            player.ClearBuff(BuffID.BabyHornet);
            player.ClearBuff(BuffID.BabyImp);
            player.ClearBuff(BuffID.BabyPenguin);
            player.ClearBuff(BuffID.BabyRedPanda);
            player.ClearBuff(BuffID.BabySkeletronHead);
            player.ClearBuff(BuffID.BabySnowman);
            player.ClearBuff(BuffID.BabyTruffle);
            player.ClearBuff(BuffID.BabyWerewolf);
            player.ClearBuff(BuffID.BlackCat);
            player.ClearBuff(BuffID.CavelingGardener);
            player.ClearBuff(BuffID.CompanionCube);
            player.ClearBuff(BuffID.CursedSapling);
            player.ClearBuff(BuffID.DirtiestBlock);
            player.ClearBuff(BuffID.DynamiteKitten);
            player.ClearBuff(BuffID.UpbeatStar);
            player.ClearBuff(BuffID.EyeballSpring);
            player.ClearBuff(BuffID.FennecFox);
            player.ClearBuff(BuffID.GlitteryButterfly);
            player.ClearBuff(BuffID.LilHarpy);
            player.ClearBuff(BuffID.MiniMinotaur);
            player.ClearBuff(BuffID.Plantero);
            player.ClearBuff(BuffID.Puppy);
            player.ClearBuff(BuffID.ShadowMimic);
            player.ClearBuff(BuffID.SharkPup);
            player.ClearBuff(BuffID.Spiffo);
            player.ClearBuff(BuffID.Squashling);
            player.ClearBuff(BuffID.TikiSpirit);
            player.ClearBuff(BuffID.VoltBunny);
            player.ClearBuff(BuffID.ZephyrFish);
            player.buffImmune[BuffID.TitaniumStorm] = true;
            player.buffImmune[BuffID.StardustGuardianMinion] = true;
            player.buffImmune[BuffID.ShadowDodge] = true;
            player.buffImmune[BuffID.BeetleEndurance1] = true;
            player.buffImmune[BuffID.BeetleEndurance2] = true;
            player.buffImmune[BuffID.BeetleEndurance3] = true;
            player.buffImmune[BuffID.BeetleMight1] = true;
            player.buffImmune[BuffID.BeetleMight2] = true;
            player.buffImmune[BuffID.BeetleMight3] = true;
            player.buffImmune[BuffID.SolarShield1] = true;
            player.buffImmune[BuffID.SolarShield2] = true;
            player.buffImmune[BuffID.SolarShield3] = true;
            player.buffImmune[BuffID.LeafCrystal] = true;
            player.buffImmune[BuffID.NebulaUpDmg1] = true;
            player.buffImmune[BuffID.NebulaUpDmg2] = true;
            player.buffImmune[BuffID.NebulaUpDmg3] = true;
            player.buffImmune[BuffID.NebulaUpLife1] = true;
            player.buffImmune[BuffID.NebulaUpLife2] = true;
            player.buffImmune[BuffID.NebulaUpLife3] = true;
            player.buffImmune[BuffID.NebulaUpMana1] = true;
            player.buffImmune[BuffID.NebulaUpMana2] = true;
            player.buffImmune[BuffID.NebulaUpMana3] = true;
            player.buffImmune[BuffID.BallistaPanic] = true;
            player.buffImmune[BuffID.RapidHealing] = true;
            player.buffImmune[BuffID.ParryDamageBuff] = true;
            player.buffImmune[BuffID.SoulDrain] = true;
            player.buffImmune[BuffID.HeartyMeal] = true;
            player.buffImmune[BuffID.CoolWhipPlayerBuff] = true;
            player.buffImmune[BuffID.ScytheWhipPlayerBuff] = true;
            player.buffImmune[BuffID.SwordWhipPlayerBuff] = true;
            player.buffImmune[BuffID.ThornWhipPlayerBuff] = true;
            player.buffImmune[BuffID.MinecartLeft] = true;
            player.buffImmune[BuffID.MinecartRight] = true;
            player.buffImmune[BuffID.MinecartLeftMech] = true;
            player.buffImmune[BuffID.MinecartRightMech] = true;
            player.buffImmune[BuffID.MinecartLeftWood] = true;
            player.buffImmune[BuffID.MinecartRightWood] = true;
            player.buffImmune[BuffID.AmberMinecartLeft] = true;
            player.buffImmune[BuffID.AmberMinecartRight] = true;
            player.buffImmune[BuffID.AmethystMinecartLeft] = true;
            player.buffImmune[BuffID.AmethystMinecartRight] = true;
            player.buffImmune[BuffID.BeeMinecartLeft] = true;
            player.buffImmune[BuffID.BeeMinecartRight] = true;
            player.buffImmune[BuffID.BeetleMinecartLeft] = true;
            player.buffImmune[BuffID.BeetleMinecartRight] = true;
            player.buffImmune[BuffID.CoffinMinecartLeft] = true;
            player.buffImmune[BuffID.CoffinMinecartRight] = true;
            player.buffImmune[BuffID.DesertMinecartLeft] = true;
            player.buffImmune[BuffID.DesertMinecartRight] = true;
            player.buffImmune[BuffID.DiamondMinecartLeft] = true;
            player.buffImmune[BuffID.DiamondMinecartRight] = true;
            player.buffImmune[BuffID.DiggingMoleMinecartLeft] = true;
            player.buffImmune[BuffID.DiggingMoleMinecartRight] = true;
            player.buffImmune[BuffID.EmeraldMinecartLeft] = true;
            player.buffImmune[BuffID.EmeraldMinecartRight] = true;
            player.buffImmune[BuffID.FartMinecartLeft] = true;
            player.buffImmune[BuffID.FartMinecartRight] = true;
            player.buffImmune[BuffID.FishMinecartLeft] = true;
            player.buffImmune[BuffID.FishMinecartRight] = true;
            player.buffImmune[BuffID.HellMinecartLeft] = true;
            player.buffImmune[BuffID.HellMinecartRight] = true;
            player.buffImmune[BuffID.LadybugMinecartLeft] = true;
            player.buffImmune[BuffID.LadybugMinecartRight] = true;
            player.buffImmune[BuffID.MeowmereMinecartLeft] = true;
            player.buffImmune[BuffID.MeowmereMinecartRight] = true;
            player.buffImmune[BuffID.PartyMinecartLeft] = true;
            player.buffImmune[BuffID.PartyMinecartRight] = true;
            player.buffImmune[BuffID.PigronMinecartLeft] = true;
            player.buffImmune[BuffID.PigronMinecartRight] = true;
            player.buffImmune[BuffID.PirateMinecartLeft] = true;
            player.buffImmune[BuffID.PirateMinecartRight] = true;
            player.buffImmune[BuffID.RubyMinecartLeft] = true;
            player.buffImmune[BuffID.RubyMinecartRight] = true;
            player.buffImmune[BuffID.SapphireMinecartLeft] = true;
            player.buffImmune[BuffID.SapphireMinecartRight] = true;
            player.buffImmune[BuffID.ShroomMinecartLeft] = true;
            player.buffImmune[BuffID.ShroomMinecartRight] = true;
            player.buffImmune[BuffID.SteampunkMinecartLeft] = true;
            player.buffImmune[BuffID.SteampunkMinecartRight] = true;
            player.buffImmune[BuffID.SunflowerMinecartLeft] = true;
            player.buffImmune[BuffID.SunflowerMinecartRight] = true;
            player.buffImmune[BuffID.TerraFartMinecartLeft] = true;
            player.buffImmune[BuffID.TerraFartMinecartRight] = true;
            player.buffImmune[BuffID.TopazMinecartLeft] = true;
            player.buffImmune[BuffID.TopazMinecartRight] = true;
            player.buffImmune[BuffID.Werewolf] = true;
            player.buffImmune[BuffID.Merfolk] = true;
            player.buffImmune[BuffID.IceBarrier] = true;
            player.buffImmune[BuffID.PaladinsShield] = true;
            player.buffImmune[BuffID.Panic] = true;
            player.buffImmune[BuffID.Cursed] = true;
            player.buffImmune[BuffID.ManaSickness] = true;
            player.buffImmune[BuffID.Silenced] = true;
            player.buffImmune[BuffID.Suffocation] = true;
            player.buffImmune[BuffID.Confused] = true;
            player.buffImmune[BuffID.VortexDebuff] = true;
            player.buffImmune[BuffID.Slow] = true;
            player.buffImmune[BuffID.OgreSpit] = true;
            player.buffImmune[BuffID.NeutralHunger] = true;
            player.buffImmune[BuffID.Hunger] = true;
            player.buffImmune[BuffID.Starving] = true;
            player.buffImmune[BuffID.Frostburn] = true;
            player.buffImmune[BuffID.ShadowFlame] = true;
            player.buffImmune[BuffID.OnFire3] = true;
            player.buffImmune[BuffID.CursedInferno] = true;
            player.buffImmune[BuffID.Chilled] = true;
            player.buffImmune[BuffID.Frozen] = true;
            player.buffImmune[BuffID.Frostburn2] = true;
            player.buffImmune[BuffID.Obstructed] = true;
            player.buffImmune[BuffID.Electrified] = true;
            player.buffImmune[BuffID.Weak] = true;
            player.buffImmune[BuffID.WitheredWeapon] = true;
            player.buffImmune[BuffID.BrokenArmor] = true;
            player.buffImmune[BuffID.WitheredArmor] = true;
            player.buffImmune[BuffID.Bleeding] = true;
            player.buffImmune[BuffID.Rabies] = true;
            player.buffImmune[BuffID.Poisoned] = true;
            player.buffImmune[BuffID.Venom] = true;
            player.buffImmune[BuffID.Burning] = true;
            player.buffImmune[BuffID.OnFire] = true;
            player.buffImmune[BuffID.Dazed] = true;
            player.fireWalk = true;
            player.noKnockback = true;
            player.buffImmune[BuffID.BoneJavelin] = true;
            player.buffImmune[BuffID.BloodButcherer] = true;
            player.buffImmune[BuffID.Midas] = true;
            player.buffImmune[BuffID.DryadsWardDebuff] = true;
            player.buffImmune[BuffID.BetsysCurse] = true;
            player.buffImmune[BuffID.Oiled] = true;
            player.buffImmune[BuffID.Daybreak] = true;
            player.buffImmune[BuffID.StardustMinionBleed] = true;
            player.buffImmune[BuffID.Slimed] = true;
            player.buffImmune[BuffID.GelBalloonBuff] = true;
            player.buffImmune[BuffID.Wet] = true;
            player.buffImmune[BuffID.Lovestruck] = true;
            player.buffImmune[BuffID.Stinky] = true;
            player.buffImmune[BuffID.Ichor] = true;
            player.buffImmune[BuffID.Webbed] = true;
            player.buffImmune[BuffID.BrainOfConfusionBuff] = true;
            player.buffImmune[BuffID.Tipsy] = true;
            player.buffImmune[BuffID.WaterCandle] = true;
            player.buffImmune[BuffID.ChaosState] = true;
            player.buffImmune[BuffID.PotionSickness] = true;
            player.buffImmune[BuffID.NoBuilding] = true;
            player.buffImmune[BuffID.WindPushed] = true;
            player.buffImmune[BuffID.MoonLeech] = true;
            player.buffImmune[BuffID.TheTongue] = true;
            player.buffImmune[BuffID.Shimmer] = true;
            player.buffImmune[BuffID.ShadowCandle] = true;
            player.npcTypeNoAggro[NPCID.EyeofCthulhu] = true;
            player.npcTypeNoAggro[NPCID.WanderingEye] = true;
            player.npcTypeNoAggro[NPCID.DemonEye] = true;
            player.npcTypeNoAggro[NPCID.DemonEyeOwl] = true;
            player.npcTypeNoAggro[NPCID.DemonEyeSpaceship] = true;
            player.npcTypeNoAggro[NPCID.EyeballFlyingFish] = true;
            player.npcTypeNoAggro[NPCID.Eyezor] = true;
            player.npcTypeNoAggro[NPCID.CataractEye] = true;
            player.npcTypeNoAggro[NPCID.DialatedEye] = true;
            player.npcTypeNoAggro[NPCID.GreenEye] = true;
            player.npcTypeNoAggro[NPCID.MoonLordFreeEye] = true;
            player.npcTypeNoAggro[NPCID.PurpleEye] = true;
            player.npcTypeNoAggro[NPCID.SleepyEye] = true;
            player.npcTypeNoAggro[NPCID.Spazmatism] = true;
            player.npcTypeNoAggro[NPCID.Retinazer] = true;
            player.npcTypeNoAggro[NPCID.SkeletronPrime] = true;
            player.npcTypeNoAggro[NPCID.PrimeCannon] = true;
            player.npcTypeNoAggro[NPCID.PrimeLaser] = true;
            player.npcTypeNoAggro[NPCID.PrimeSaw] = true;
            player.npcTypeNoAggro[NPCID.PrimeVice] = true;
            player.npcTypeNoAggro[NPCID.MoonLordCore] = true;
            player.npcTypeNoAggro[NPCID.MoonLordFreeEye] = true;
            player.npcTypeNoAggro[NPCID.MoonLordHand] = true;
            player.npcTypeNoAggro[NPCID.MoonLordHead] = true;
            player.npcTypeNoAggro[NPCID.MoonLordLeechBlob] = true;
            player.npcTypeNoAggro[NPCID.CultistArcherBlue] = true;
            player.npcTypeNoAggro[NPCID.CultistArcherWhite] = true;
            player.npcTypeNoAggro[NPCID.CultistBoss] = true;
            player.npcTypeNoAggro[NPCID.CultistBossClone] = true;
            player.npcTypeNoAggro[NPCID.CultistDevote] = true;
            player.npcTypeNoAggro[NPCID.CultistTablet] = true;
            player.npcTypeNoAggro[NPCID.AncientCultistSquidhead] = true;
            player.npcTypeNoAggro[NPCID.AncientDoom] = true;
            player.npcTypeNoAggro[NPCID.CultistDragonHead] = true;
            player.npcTypeNoAggro[NPCID.CultistDragonBody1] = true;
            player.npcTypeNoAggro[NPCID.CultistDragonBody2] = true;
            player.npcTypeNoAggro[NPCID.CultistDragonBody3] = true;
            player.npcTypeNoAggro[NPCID.CultistDragonBody4] = true;
            player.npcTypeNoAggro[NPCID.CultistDragonTail] = true;
            player.npcTypeNoAggro[NPCID.Zombie] = true;
            player.npcTypeNoAggro[NPCID.ZombieEskimo] = true;
            player.npcTypeNoAggro[NPCID.ZombieDoctor] = true;
            player.npcTypeNoAggro[NPCID.ZombieElf] = true;
            player.npcTypeNoAggro[NPCID.ZombieElfBeard] = true;
            player.npcTypeNoAggro[NPCID.PincushionZombie] = true;
            player.npcTypeNoAggro[NPCID.TorchZombie] = true;
            player.npcTypeNoAggro[NPCID.ZombieElfGirl] = true;
            player.npcTypeNoAggro[NPCID.ZombieMerman] = true;
            player.npcTypeNoAggro[NPCID.ZombieElfGirl] = true;
            player.npcTypeNoAggro[NPCID.ZombieMushroom] = true;
            player.npcTypeNoAggro[NPCID.ZombieMushroomHat] = true;
            player.npcTypeNoAggro[NPCID.ZombiePixie] = true;
            player.npcTypeNoAggro[NPCID.ZombieRaincoat] = true;
            player.npcTypeNoAggro[NPCID.ZombieSuperman] = true;
            player.npcTypeNoAggro[NPCID.ZombieXmas] = true;
            player.npcTypeNoAggro[NPCID.ArmedZombie] = true;
            player.npcTypeNoAggro[NPCID.ArmedTorchZombie] = true;
            player.npcTypeNoAggro[NPCID.ZombieSweater] = true;
            player.npcTypeNoAggro[NPCID.ArmedZombieCenx] = true;
            player.npcTypeNoAggro[NPCID.ArmedZombiePincussion] = true;
            player.npcTypeNoAggro[NPCID.ArmedZombieEskimo] = true;
            player.npcTypeNoAggro[NPCID.ArmedZombieSlimed] = true;
            player.npcTypeNoAggro[NPCID.ArmedZombieSwamp] = true;
            player.npcTypeNoAggro[NPCID.ArmedZombieTwiggy] = true;
            player.npcTypeNoAggro[NPCID.BaldZombie] = true;
            player.npcTypeNoAggro[NPCID.BloodZombie] = true;
            player.npcTypeNoAggro[NPCID.FemaleZombie] = true;
            player.npcTypeNoAggro[NPCID.MaggotZombie] = true;
            player.npcTypeNoAggro[NPCID.SlimedZombie] = true;
            player.npcTypeNoAggro[NPCID.TorchZombie] = true;
            player.npcTypeNoAggro[NPCID.TwiggyZombie] = true;
            player.npcTypeNoAggro[NPCID.Skeleton] = true;
            player.npcTypeNoAggro[NPCID.SkeletonAlien] = true;
            player.npcTypeNoAggro[NPCID.SkeletonArcher] = true;
            player.npcTypeNoAggro[NPCID.SkeletonAstonaut] = true;
            player.npcTypeNoAggro[NPCID.SkeletonCommando] = true;
            player.npcTypeNoAggro[NPCID.SkeletonSniper] = true;
            player.npcTypeNoAggro[NPCID.SkeletonTopHat] = true;
            player.npcTypeNoAggro[NPCID.ArmoredSkeleton] = true;
            player.npcTypeNoAggro[NPCID.BoneThrowingSkeleton] = true;
            player.npcTypeNoAggro[NPCID.BoneThrowingSkeleton2] = true;
            player.npcTypeNoAggro[NPCID.BoneThrowingSkeleton3] = true;
            player.npcTypeNoAggro[NPCID.BoneThrowingSkeleton4] = true;
            player.npcTypeNoAggro[NPCID.DD2SkeletonT1] = true;
            player.npcTypeNoAggro[NPCID.DD2SkeletonT3] = true;
            player.npcTypeNoAggro[NPCID.GreekSkeleton] = true;
            player.npcTypeNoAggro[NPCID.HeadacheSkeleton] = true;
            player.npcTypeNoAggro[NPCID.MisassembledSkeleton] = true;
            player.npcTypeNoAggro[NPCID.SporeSkeleton] = true;
            player.npcTypeNoAggro[NPCID.TacticalSkeleton] = true;
            player.npcTypeNoAggro[NPCID.SkeletronHand] = true;
            player.npcTypeNoAggro[NPCID.SkeletronHead] = true;
            player.npcTypeNoAggro[NPCID.DungeonGuardian] = true;
            player.npcTypeNoAggro[NPCID.Ghost] = true;
            player.npcTypeNoAggro[NPCID.PirateGhost] = true;
            player.npcTypeNoAggro[NPCID.FloatyGross] = true;
            player.npcTypeNoAggro[NPCID.Wraith] = true;
            player.npcTypeNoAggro[NPCID.BoneSerpentBody] = true;
            player.npcTypeNoAggro[NPCID.BoneSerpentHead] = true;
            player.npcTypeNoAggro[NPCID.BoneSerpentTail] = true;
            player.npcTypeNoAggro[NPCID.BoneLee] = true;
            player.npcTypeNoAggro[NPCID.CursedSkull] = true;
            player.npcTypeNoAggro[NPCID.GiantCursedSkull] = true;
            player.npcTypeNoAggro[NPCID.UndeadMiner] = true;
            player.npcTypeNoAggro[NPCID.UndeadViking] = true;
            player.npcTypeNoAggro[NPCID.ArmoredViking] = true;
            player.npcTypeNoAggro[NPCID.BlueArmoredBones] = true;
            player.npcTypeNoAggro[NPCID.BlueArmoredBonesMace] = true;
            player.npcTypeNoAggro[NPCID.BlueArmoredBonesSword] = true;
            player.npcTypeNoAggro[NPCID.BlueArmoredBonesNoPants] = true;
            player.npcTypeNoAggro[NPCID.DarkCaster] = true;
            player.npcTypeNoAggro[NPCID.DarkMummy] = true;
            player.npcTypeNoAggro[NPCID.LightMummy] = true;
            player.npcTypeNoAggro[NPCID.Mummy] = true;
            player.npcTypeNoAggro[NPCID.RustyArmoredBonesAxe] = true;
            player.npcTypeNoAggro[NPCID.RustyArmoredBonesFlail] = true;
            player.npcTypeNoAggro[NPCID.RustyArmoredBonesSword] = true;
            player.npcTypeNoAggro[NPCID.RustyArmoredBonesSwordNoArmor] = true;
            player.npcTypeNoAggro[NPCID.HellArmoredBones] = true;
            player.npcTypeNoAggro[NPCID.HellArmoredBonesMace] = true;
            player.npcTypeNoAggro[NPCID.HellArmoredBonesSword] = true;
            player.npcTypeNoAggro[NPCID.HellArmoredBonesSpikeShield] = true;
            player.npcTypeNoAggro[NPCID.DiabolistRed] = true;
            player.npcTypeNoAggro[NPCID.DiabolistWhite] = true;
            player.npcTypeNoAggro[NPCID.Necromancer] = true;
            player.npcTypeNoAggro[NPCID.NecromancerArmored] = true;
            player.npcTypeNoAggro[NPCID.RaggedCaster] = true;
            player.npcTypeNoAggro[NPCID.RaggedCasterOpenCoat] = true;
            player.npcTypeNoAggro[NPCID.AngryBones] = true;
            player.npcTypeNoAggro[NPCID.AngryBonesBig] = true;
            player.npcTypeNoAggro[NPCID.AngryBonesBigHelmet] = true;
            player.npcTypeNoAggro[NPCID.AngryBonesBigMuscle] = true;
            player.npcTypeNoAggro[NPCID.DoctorBones] = true;
            player.npcTypeNoAggro[NPCID.TheBride] = true;
            player.npcTypeNoAggro[NPCID.TheGroom] = true;
            player.npcTypeNoAggro[NPCID.Reaper] = true;
            player.npcTypeNoAggro[NPCID.Eyezor] = true;
            player.npcTypeNoAggro[NPCID.CreatureFromTheDeep] = true;
            player.npcTypeNoAggro[NPCID.ThePossessed] = true;
            player.npcTypeNoAggro[NPCID.PossessedArmor] = true;
            player.npcTypeNoAggro[NPCID.Poltergeist] = true;
            player.npcTypeNoAggro[NPCID.SwampThing] = true;
            player.npcTypeNoAggro[NPCID.WallofFlesh] = true;
            player.npcTypeNoAggro[NPCID.WallofFleshEye] = true;
            player.npcTypeNoAggro[NPCID.TheHungry] = true;
            player.npcTypeNoAggro[NPCID.TheHungryII] = true;
            player.npcTypeNoAggro[NPCID.Demon] = true;
            player.npcTypeNoAggro[NPCID.VoodooDemon] = true;
            player.npcTypeNoAggro[NPCID.Hellbat] = true; //redundant in PAM
            player.npcTypeNoAggro[NPCID.Lavabat] = true; //redundant in PAM 
            player.npcTypeNoAggro[NPCID.LavaSlime] = true; //redundant in PAM
            player.npcTypeNoAggro[NPCID.RedDevil] = true;
            player.npcTypeNoAggro[NPCID.FireImp] = true;
            player.npcTypeNoAggro[NPCID.BoneSerpentBody] = true; //redundant in PAM
            player.npcTypeNoAggro[NPCID.BoneSerpentHead] = true; //redundant in PAM
            player.npcTypeNoAggro[NPCID.BoneSerpentTail] = true; //redundant in PAM
            player.npcTypeNoAggro[NPCID.Plantera] = true;
            player.npcTypeNoAggro[NPCID.PlanterasHook] = true;
            player.npcTypeNoAggro[NPCID.PlanterasTentacle] = true;
            player.npcTypeNoAggro[NPCID.JungleBat] = true; //redundant in PAM
            player.npcTypeNoAggro[NPCID.JungleCreeper] = true;
            player.npcTypeNoAggro[NPCID.JungleCreeperWall] = true;
            player.npcTypeNoAggro[NPCID.SpikedJungleSlime] = true;//redundant in PAM
            player.npcTypeNoAggro[NPCID.Piranha] = true;
            player.npcTypeNoAggro[NPCID.Snatcher] = true;
            player.npcTypeNoAggro[NPCID.ManEater] = true;
            player.npcTypeNoAggro[NPCID.DoctorBones] = true; //redundant in PAM
            player.npcTypeNoAggro[NPCID.AngryTrapper] = true;
            player.npcTypeNoAggro[NPCID.GiantTortoise] = true;
            player.npcTypeNoAggro[NPCID.GiantFlyingFox] = true; //redundant in PAM
            player.npcTypeNoAggro[NPCID.Hornet] = true;
            player.npcTypeNoAggro[NPCID.Arapaima] = true;
            player.npcTypeNoAggro[NPCID.AnglerFish] = true;
            player.npcTypeNoAggro[NPCID.LacBeetle] = true; //redundant in PAM
            player.npcTypeNoAggro[NPCID.Moth] = true;
            player.npcTypeNoAggro[NPCID.MossHornet] = true;
            player.npcTypeNoAggro[NPCID.Hornet] = true;
            player.npcTypeNoAggro[NPCID.HornetFatty] = true;
            player.npcTypeNoAggro[NPCID.HornetHoney] = true;
            player.npcTypeNoAggro[NPCID.HornetStingy] = true;
            player.npcTypeNoAggro[NPCID.HornetLeafy] = true;
            player.npcTypeNoAggro[NPCID.HornetSpikey] = true;
            player.npcTypeNoAggro[NPCID.Crab] = true;
            player.npcTypeNoAggro[NPCID.Shark] = true;
            player.npcTypeNoAggro[NPCID.Sharkron] = true;
            player.npcTypeNoAggro[NPCID.Sharkron2] = true;
            player.npcTypeNoAggro[NPCID.Squid] = true;
            player.npcTypeNoAggro[NPCID.SeaSnail] = true;
            player.npcTypeNoAggro[NPCID.Pixie] = true;
            player.npcTypeNoAggro[NPCID.Unicorn] = true;
            player.npcTypeNoAggro[NPCID.RainbowSlime] = true;
            player.npcTypeNoAggro[NPCID.Gastropod] = true;
            player.npcTypeNoAggro[NPCID.LightMummy] = true;
            player.npcTypeNoAggro[NPCID.IlluminantSlime] = true;
            player.npcTypeNoAggro[NPCID.IlluminantBat] = true;
            player.npcTypeNoAggro[NPCID.ChaosElemental] = true;
            player.npcTypeNoAggro[NPCID.EnchantedSword] = true;
            player.npcTypeNoAggro[NPCID.BigMimicHallow] = true;
            player.npcTypeNoAggro[NPCID.DesertGhoulHallow] = true;
            player.npcTypeNoAggro[NPCID.PigronHallow] = true;
            player.npcTypeNoAggro[NPCID.SandsharkHallow] = true;
            player.npcTypeNoAggro[NPCID.EaterofSouls] = true;
            player.npcTypeNoAggro[NPCID.EaterofWorldsBody] = true;
            player.npcTypeNoAggro[NPCID.EaterofWorldsHead] = true;
            player.npcTypeNoAggro[NPCID.EaterofWorldsTail] = true;
            player.npcTypeNoAggro[NPCID.VileSpitEaterOfWorlds] = true;
            player.npcTypeNoAggro[NPCID.VileSpit] = true;
            player.npcTypeNoAggro[NPCID.CorruptBunny] = true;
            player.npcTypeNoAggro[NPCID.CorruptGoldfish] = true;
            player.npcTypeNoAggro[NPCID.CorruptPenguin] = true;
            player.npcTypeNoAggro[NPCID.DevourerBody] = true;
            player.npcTypeNoAggro[NPCID.DevourerHead] = true;
            player.npcTypeNoAggro[NPCID.DevourerTail] = true;
            player.npcTypeNoAggro[NPCID.Corruptor] = true;
            player.npcTypeNoAggro[NPCID.CorruptSlime] = true;
            player.npcTypeNoAggro[NPCID.Slimer] = true;
            player.npcTypeNoAggro[NPCID.SeekerBody] = true;
            player.npcTypeNoAggro[NPCID.SeekerHead] = true;
            player.npcTypeNoAggro[NPCID.SeekerTail] = true;
            player.npcTypeNoAggro[NPCID.DarkMummy] = true;
            player.npcTypeNoAggro[NPCID.CursedHammer] = true;
            player.npcTypeNoAggro[NPCID.Clinger] = true;
            player.npcTypeNoAggro[NPCID.BigMimicCorruption] = true;
            player.npcTypeNoAggro[NPCID.DesertGhoulCorruption] = true;
            player.npcTypeNoAggro[NPCID.PigronCorruption] = true;
            player.npcTypeNoAggro[NPCID.BloodCrawler] = true;
            player.npcTypeNoAggro[NPCID.BloodCrawlerWall] = true;
            player.npcTypeNoAggro[NPCID.FaceMonster] = true;
            player.npcTypeNoAggro[NPCID.CrimsonBunny] = true;
            player.npcTypeNoAggro[NPCID.CrimsonGoldfish] = true;
            player.npcTypeNoAggro[NPCID.CrimsonPenguin] = true;
            player.npcTypeNoAggro[NPCID.BigMimicCrimson] = true;
            player.npcTypeNoAggro[NPCID.SandsharkCrimson] = true;
            player.npcTypeNoAggro[NPCID.SandsharkCorrupt] = true;
            player.npcTypeNoAggro[NPCID.DesertGhoulCrimson] = true;
            player.npcTypeNoAggro[NPCID.PigronCrimson] = true;
            player.npcTypeNoAggro[NPCID.Crimera] = true;
            player.npcTypeNoAggro[NPCID.BrainofCthulhu] = true;
            player.npcTypeNoAggro[NPCID.Creeper] = true;
            player.npcTypeNoAggro[NPCID.Herpling] = true;
            player.npcTypeNoAggro[NPCID.Crimslime] = true;
            player.npcTypeNoAggro[NPCID.BloodJelly] = true;
            player.npcTypeNoAggro[NPCID.BloodFeeder] = true;
            player.npcTypeNoAggro[NPCID.BloodMummy] = true;
            player.npcTypeNoAggro[NPCID.CrimsonAxe] = true;
            player.npcTypeNoAggro[NPCID.IchorSticker] = true;
            player.npcTypeNoAggro[NPCID.FloatyGross] = true;
            player.npcTypeNoAggro[NPCID.DesertGhoulCrimson] = true;
            player.npcTypeNoAggro[NPCID.BigMimicCrimson] = true;
            player.npcTypeNoAggro[NPCID.PigronCrimson] = true;
            player.npcTypeNoAggro[NPCID.Deerclops] = true;
            player.npcTypeNoAggro[NPCID.AngryNimbus] = true;
            player.npcTypeNoAggro[NPCID.FlyingFish] = true;
            player.npcTypeNoAggro[NPCID.IceGolem] = true;
            player.npcTypeNoAggro[NPCID.RainbowSlime] = true;
            player.npcTypeNoAggro[NPCID.ZombieRaincoat] = true;
            player.npcTypeNoAggro[NPCID.UmbrellaSlime] = true;
            player.npcTypeNoAggro[NPCID.IceSlime] = true;
            player.npcTypeNoAggro[NPCID.ZombieEskimo] = true;
            player.npcTypeNoAggro[NPCID.ArmedZombieEskimo] = true;
            player.npcTypeNoAggro[NPCID.CorruptPenguin] = true;
            player.npcTypeNoAggro[NPCID.CrimsonPenguin] = true;
            player.npcTypeNoAggro[NPCID.IceElemental] = true;
            player.npcTypeNoAggro[NPCID.Wolf] = true;
            player.npcTypeNoAggro[NPCID.IceBat] = true;
            player.npcTypeNoAggro[NPCID.SnowFlinx] = true;
            player.npcTypeNoAggro[NPCID.IceSlime] = true;
            player.npcTypeNoAggro[NPCID.UndeadViking] = true;
            player.npcTypeNoAggro[NPCID.CyanBeetle] = true;
            player.npcTypeNoAggro[NPCID.ArmoredViking] = true;
            player.npcTypeNoAggro[NPCID.IceTortoise] = true;
            player.npcTypeNoAggro[NPCID.IcyMerman] = true;
            player.npcTypeNoAggro[NPCID.IceMimic] = true;
            player.npcTypeNoAggro[NPCID.PigronCorruption] = true;
            player.npcTypeNoAggro[NPCID.PigronCrimson] = true;
            player.npcTypeNoAggro[NPCID.PigronHallow] = true;
            player.npcTypeNoAggro[NPCID.IceElemental] = true;
            player.npcTypeNoAggro[NPCID.QueenSlimeBoss] = true;
            player.npcTypeNoAggro[NPCID.QueenSlimeMinionBlue] = true;
            player.npcTypeNoAggro[NPCID.QueenSlimeMinionPink] = true;
            player.npcTypeNoAggro[NPCID.QueenSlimeMinionPurple] = true;
            player.npcTypeNoAggro[NPCID.KingSlime] = true;
            player.npcTypeNoAggro[NPCID.SlimeSpiked] = true;
            player.npcTypeNoAggro[NPCID.QueenBee] = true;
            player.npcTypeNoAggro[NPCID.BlueSlime] = true;
            player.npcTypeNoAggro[NPCID.IceSlime] = true;
            player.npcTypeNoAggro[NPCID.SandSlime] = true;
            player.npcTypeNoAggro[NPCID.SpikedIceSlime] = true;
            player.npcTypeNoAggro[NPCID.SpikedJungleSlime] = true;
            player.npcTypeNoAggro[NPCID.MotherSlime] = true;
            player.npcTypeNoAggro[NPCID.LavaSlime] = true;
            player.npcTypeNoAggro[NPCID.DungeonSlime] = true;
            player.npcTypeNoAggro[NPCID.GoldenSlime] = true;
            player.npcTypeNoAggro[NPCID.UmbrellaSlime] = true;
            player.npcTypeNoAggro[NPCID.ShimmerSlime] = true;
            player.npcTypeNoAggro[NPCID.SlimeMasked] = true;
            player.npcTypeNoAggro[NPCID.SlimeRibbonGreen] = true;
            player.npcTypeNoAggro[NPCID.SlimeRibbonRed] = true;
            player.npcTypeNoAggro[NPCID.SlimeRibbonWhite] = true;
            player.npcTypeNoAggro[NPCID.SlimeRibbonYellow] = true;
            player.npcTypeNoAggro[NPCID.ToxicSludge] = true;
            player.npcTypeNoAggro[NPCID.CorruptSlime] = true;
            player.npcTypeNoAggro[NPCID.Slimer] = true;
            player.npcTypeNoAggro[NPCID.Crimslime] = true;
            player.npcTypeNoAggro[NPCID.IlluminantSlime] = true;
            player.npcTypeNoAggro[NPCID.RainbowSlime] = true;
            player.npcTypeNoAggro[NPCID.Bee] = true;
            player.npcTypeNoAggro[NPCID.BeeSmall] = true;
            player.npcTypeNoAggro[NPCID.Hornet] = true;
            player.npcTypeNoAggro[NPCID.HornetFatty] = true;
            player.npcTypeNoAggro[NPCID.HornetHoney] = true;
            player.npcTypeNoAggro[NPCID.HornetLeafy] = true;
            player.npcTypeNoAggro[NPCID.HornetSpikey] = true;
            player.npcTypeNoAggro[NPCID.HornetStingy] = true;
            player.npcTypeNoAggro[NPCID.MossHornet] = true;
            player.npcTypeNoAggro[NPCID.SlimeMasked] = true;
            player.npcTypeNoAggro[NPCID.SlimeRibbonGreen] = true;
            player.npcTypeNoAggro[NPCID.SlimeRibbonRed] = true;
            player.npcTypeNoAggro[NPCID.SlimeRibbonWhite] = true;
            player.npcTypeNoAggro[NPCID.SlimeRibbonYellow] = true;
            player.npcTypeNoAggro[NPCID.ZombieDoctor] = true;
            player.npcTypeNoAggro[NPCID.ZombieSuperman] = true;
            player.npcTypeNoAggro[NPCID.ZombiePixie] = true;
            player.npcTypeNoAggro[NPCID.SkeletonTopHat] = true;
            player.npcTypeNoAggro[NPCID.SkeletonAstonaut] = true;
            player.npcTypeNoAggro[NPCID.SkeletonAlien] = true;
            player.npcTypeNoAggro[NPCID.ZombieXmas] = true;
            player.npcTypeNoAggro[NPCID.ZombieSweater] = true;
            player.npcTypeNoAggro[NPCID.GoblinArcher] = true;
            player.npcTypeNoAggro[NPCID.GoblinPeon] = true;
            player.npcTypeNoAggro[NPCID.GoblinScout] = true;
            player.npcTypeNoAggro[NPCID.GoblinSorcerer] = true;
            player.npcTypeNoAggro[NPCID.GoblinSummoner] = true;
            player.npcTypeNoAggro[NPCID.GoblinThief] = true;
            player.npcTypeNoAggro[NPCID.GoblinWarrior] = true;
            player.npcTypeNoAggro[NPCID.ShadowFlameApparition] = true;
            player.npcTypeNoAggro[NPCID.DD2DrakinT2] = true;
            player.npcTypeNoAggro[NPCID.DD2DrakinT3] = true;
            player.npcTypeNoAggro[NPCID.DD2AttackerTest] = true;
            player.npcTypeNoAggro[NPCID.DD2Bartender] = true;
            player.npcTypeNoAggro[NPCID.DD2Betsy] = true;
            player.npcTypeNoAggro[NPCID.DD2DarkMageT1] = true;
            player.npcTypeNoAggro[NPCID.DD2DarkMageT3] = true;
            player.npcTypeNoAggro[NPCID.DD2EterniaCrystal] = true;
            player.npcTypeNoAggro[NPCID.DD2GoblinBomberT1] = true;
            player.npcTypeNoAggro[NPCID.DD2GoblinBomberT2] = true;
            player.npcTypeNoAggro[NPCID.DD2GoblinBomberT3] = true;
            player.npcTypeNoAggro[NPCID.DD2GoblinT1] = true;
            player.npcTypeNoAggro[NPCID.DD2GoblinT2] = true;
            player.npcTypeNoAggro[NPCID.DD2GoblinT3] = true;
            player.npcTypeNoAggro[NPCID.DD2JavelinstT1] = true;
            player.npcTypeNoAggro[NPCID.DD2JavelinstT2] = true;
            player.npcTypeNoAggro[NPCID.DD2JavelinstT3] = true;
            player.npcTypeNoAggro[NPCID.DD2KoboldFlyerT2] = true;
            player.npcTypeNoAggro[NPCID.DD2KoboldFlyerT3] = true;
            player.npcTypeNoAggro[NPCID.DD2KoboldWalkerT2] = true;
            player.npcTypeNoAggro[NPCID.DD2KoboldWalkerT3] = true;
            player.npcTypeNoAggro[NPCID.DD2LanePortal] = true;
            player.npcTypeNoAggro[NPCID.DD2LightningBugT3] = true;
            player.npcTypeNoAggro[NPCID.DD2OgreT2] = true;
            player.npcTypeNoAggro[NPCID.DD2OgreT3] = true;
            player.npcTypeNoAggro[NPCID.DD2SkeletonT1] = true;
            player.npcTypeNoAggro[NPCID.DD2SkeletonT3] = true;
            player.npcTypeNoAggro[NPCID.DD2WitherBeastT2] = true;
            player.npcTypeNoAggro[NPCID.DD2WitherBeastT3] = true;
            player.npcTypeNoAggro[NPCID.DD2WyvernT1] = true;
            player.npcTypeNoAggro[NPCID.DD2WyvernT2] = true;
            player.npcTypeNoAggro[NPCID.DD2WyvernT3] = true;
            player.npcTypeNoAggro[NPCID.MisterStabby] = true;
            player.npcTypeNoAggro[NPCID.SnowBalla] = true;
            player.npcTypeNoAggro[NPCID.SnowmanGangsta] = true;
            player.npcTypeNoAggro[NPCID.Parrot] = true;
            player.npcTypeNoAggro[NPCID.PirateCaptain] = true;
            player.npcTypeNoAggro[NPCID.PirateCorsair] = true;
            player.npcTypeNoAggro[NPCID.PirateCrossbower] = true;
            player.npcTypeNoAggro[NPCID.PirateDeadeye] = true;
            player.npcTypeNoAggro[NPCID.PirateDeckhand] = true;
            player.npcTypeNoAggro[NPCID.PirateGhost] = true;
            player.npcTypeNoAggro[NPCID.PirateShip] = true;
            player.npcTypeNoAggro[NPCID.PirateShipCannon] = true;
            player.npcTypeNoAggro[NPCID.Mothron] = true;
            player.npcTypeNoAggro[NPCID.MothronEgg] = true;
            player.npcTypeNoAggro[NPCID.MothronSpawn] = true;
            player.npcTypeNoAggro[NPCID.Butcher] = true;
            player.npcTypeNoAggro[NPCID.CreatureFromTheDeep] = true;
            player.npcTypeNoAggro[NPCID.DeadlySphere] = true;
            player.npcTypeNoAggro[NPCID.DrManFly] = true;
            player.npcTypeNoAggro[NPCID.Eyezor] = true;
            player.npcTypeNoAggro[NPCID.Frankenstein] = true;
            player.npcTypeNoAggro[NPCID.Fritz] = true;
            player.npcTypeNoAggro[NPCID.Nailhead] = true;
            player.npcTypeNoAggro[NPCID.Psycho] = true;
            player.npcTypeNoAggro[NPCID.Reaper] = true;
            player.npcTypeNoAggro[NPCID.SwampThing] = true;
            player.npcTypeNoAggro[NPCID.ThePossessed] = true;
            player.npcTypeNoAggro[NPCID.Vampire] = true;
            player.npcTypeNoAggro[NPCID.VampireBat] = true;
            player.npcTypeNoAggro[NPCID.BrainScrambler] = true;
            player.npcTypeNoAggro[NPCID.GigaZapper] = true;
            player.npcTypeNoAggro[NPCID.GrayGrunt] = true;
            player.npcTypeNoAggro[NPCID.MartianDrone] = true;
            player.npcTypeNoAggro[NPCID.MartianEngineer] = true;
            player.npcTypeNoAggro[NPCID.MartianOfficer] = true;
            player.npcTypeNoAggro[NPCID.MartianProbe] = true;
            player.npcTypeNoAggro[NPCID.MartianSaucer] = true;
            player.npcTypeNoAggro[NPCID.MartianSaucerCannon] = true;
            player.npcTypeNoAggro[NPCID.MartianSaucerCore] = true;
            player.npcTypeNoAggro[NPCID.MartianSaucerTurret] = true;
            player.npcTypeNoAggro[NPCID.MartianTurret] = true;
            player.npcTypeNoAggro[NPCID.MartianWalker] = true;
            player.npcTypeNoAggro[NPCID.RayGunner] = true;
            player.npcTypeNoAggro[NPCID.Scutlix] = true;
            player.npcTypeNoAggro[NPCID.ScutlixRider] = true;
            player.npcTypeNoAggro[NPCID.HeadlessHorseman] = true;
            player.npcTypeNoAggro[NPCID.Hellhound] = true;
            player.npcTypeNoAggro[NPCID.Poltergeist] = true;
            player.npcTypeNoAggro[NPCID.Scarecrow1] = true;
            player.npcTypeNoAggro[NPCID.Scarecrow10] = true;
            player.npcTypeNoAggro[NPCID.Scarecrow2] = true;
            player.npcTypeNoAggro[NPCID.Scarecrow3] = true;
            player.npcTypeNoAggro[NPCID.Scarecrow4] = true;
            player.npcTypeNoAggro[NPCID.Scarecrow5] = true;
            player.npcTypeNoAggro[NPCID.Scarecrow6] = true;
            player.npcTypeNoAggro[NPCID.Scarecrow7] = true;
            player.npcTypeNoAggro[NPCID.Scarecrow8] = true;
            player.npcTypeNoAggro[NPCID.Scarecrow9] = true;
            player.npcTypeNoAggro[NPCID.Splinterling] = true;
            player.npcTypeNoAggro[NPCID.Pumpking] = true;
            player.npcTypeNoAggro[NPCID.PumpkingBlade] = true;
            player.npcTypeNoAggro[NPCID.ElfArcher] = true;
            player.npcTypeNoAggro[NPCID.ElfCopter] = true;
            player.npcTypeNoAggro[NPCID.Flocko] = true;
            player.npcTypeNoAggro[NPCID.GingerbreadMan] = true;
            player.npcTypeNoAggro[NPCID.Krampus] = true;
            player.npcTypeNoAggro[NPCID.Nutcracker] = true;
            player.npcTypeNoAggro[NPCID.NutcrackerSpinning] = true;
            player.npcTypeNoAggro[NPCID.PresentMimic] = true;
            player.npcTypeNoAggro[NPCID.Yeti] = true;
            player.npcTypeNoAggro[NPCID.ZombieElf] = true;
            player.npcTypeNoAggro[NPCID.ZombieElfBeard] = true;
            player.npcTypeNoAggro[NPCID.ZombieElfGirl] = true;
            player.npcTypeNoAggro[NPCID.Everscream] = true;
            player.npcTypeNoAggro[NPCID.SantaNK1] = true;
            player.npcTypeNoAggro[NPCID.Everscream] = true;
            player.npcTypeNoAggro[NPCID.IceQueen] = true;
            player.npcTypeNoAggro[NPCID.LunarTowerNebula] = true;
            player.npcTypeNoAggro[NPCID.LunarTowerSolar] = true;
            player.npcTypeNoAggro[NPCID.LunarTowerStardust] = true;
            player.npcTypeNoAggro[NPCID.LunarTowerVortex] = true;
            player.npcTypeNoAggro[NPCID.NebulaBrain] = true;
            player.npcTypeNoAggro[NPCID.NebulaBeast] = true;
            player.npcTypeNoAggro[NPCID.NebulaHeadcrab] = true;
            player.npcTypeNoAggro[NPCID.NebulaSoldier] = true;
            player.npcTypeNoAggro[NPCID.SolarCorite] = true;
            player.npcTypeNoAggro[NPCID.SolarCrawltipedeBody] = true;
            player.npcTypeNoAggro[NPCID.SolarCrawltipedeHead] = true;
            player.npcTypeNoAggro[NPCID.SolarCrawltipedeTail] = true;
            player.npcTypeNoAggro[NPCID.SolarDrakomire] = true;
            player.npcTypeNoAggro[NPCID.SolarDrakomireRider] = true;
            player.npcTypeNoAggro[NPCID.SolarFlare] = true;
            player.npcTypeNoAggro[NPCID.SolarGoop] = true;
            player.npcTypeNoAggro[NPCID.SolarSolenian] = true;
            player.npcTypeNoAggro[NPCID.SolarSpearman] = true;
            player.npcTypeNoAggro[NPCID.SolarSroller] = true;
            player.npcTypeNoAggro[NPCID.StardustCellBig] = true;
            player.npcTypeNoAggro[NPCID.StardustCellSmall] = true;
            player.npcTypeNoAggro[NPCID.StardustJellyfishBig] = true;
            player.npcTypeNoAggro[NPCID.StardustJellyfishSmall] = true;
            player.npcTypeNoAggro[NPCID.StardustSoldier] = true;
            player.npcTypeNoAggro[NPCID.StardustSpiderBig] = true;
            player.npcTypeNoAggro[NPCID.StardustSpiderSmall] = true;
            player.npcTypeNoAggro[NPCID.StardustWormBody] = true;
            player.npcTypeNoAggro[NPCID.StardustWormHead] = true;
            player.npcTypeNoAggro[NPCID.StardustWormTail] = true;
            player.npcTypeNoAggro[NPCID.VortexHornet] = true;
            player.npcTypeNoAggro[NPCID.VortexHornetQueen] = true;
            player.npcTypeNoAggro[NPCID.VortexLarva] = true;
            player.npcTypeNoAggro[NPCID.VortexRifleman] = true;
            player.npcTypeNoAggro[NPCID.VortexSoldier] = true;
            player.npcTypeNoAggro[NPCID.Gnome] = true;
            player.npcTypeNoAggro[NPCID.CaveBat] = true;
            player.npcTypeNoAggro[NPCID.SporeBat] = true;
            player.npcTypeNoAggro[NPCID.JungleBat] = true;
            player.npcTypeNoAggro[NPCID.Hellbat] = true;
            player.npcTypeNoAggro[NPCID.IceBat] = true;
            player.npcTypeNoAggro[NPCID.GiantBat] = true;
            player.npcTypeNoAggro[NPCID.IlluminantBat] = true;
            player.npcTypeNoAggro[NPCID.Lavabat] = true;
            player.npcTypeNoAggro[NPCID.Slimer] = true;
            player.npcTypeNoAggro[NPCID.GiantFlyingFox] = true;
            player.npcTypeNoAggro[NPCID.VampireBat] = true;
            player.npcTypeNoAggro[NPCID.AnomuraFungus] = true;
            player.npcTypeNoAggro[NPCID.FungiBulb] = true;
            player.npcTypeNoAggro[NPCID.FungiSpore] = true;
            player.npcTypeNoAggro[NPCID.FungoFish] = true;
            player.npcTypeNoAggro[NPCID.GiantFungiBulb] = true;
            player.npcTypeNoAggro[NPCID.SporeBat] = true;
            player.npcTypeNoAggro[NPCID.SporeSkeleton] = true;
            player.npcTypeNoAggro[NPCID.MushiLadybug] = true;
            player.npcTypeNoAggro[NPCID.ZombieMushroom] = true;
            player.npcTypeNoAggro[NPCID.Vulture] = true;
            player.npcTypeNoAggro[NPCID.Antlion] = true;
            player.npcTypeNoAggro[NPCID.Mummy] = true;
            player.npcTypeNoAggro[NPCID.LightMummy] = true;
            player.npcTypeNoAggro[NPCID.DarkMummy] = true;
            player.npcTypeNoAggro[NPCID.BloodMummy] = true;
            player.npcTypeNoAggro[NPCID.Golfer] = true;
            player.npcTypeNoAggro[NPCID.GolferRescue] = true;
            player.npcTypeNoAggro[NPCID.FlyingAntlion] = true;
            player.npcTypeNoAggro[NPCID.GiantFlyingAntlion] = true;
            player.npcTypeNoAggro[NPCID.GiantWalkingAntlion] = true;
            player.npcTypeNoAggro[NPCID.BloodNautilus] = true;
            player.npcTypeNoAggro[NPCID.LarvaeAntlion] = true;
            player.npcTypeNoAggro[NPCID.WalkingAntlion] = true;
            player.npcTypeNoAggro[NPCID.SandSlime] = true;
            player.npcTypeNoAggro[NPCID.DesertBeast] = true;
            player.npcTypeNoAggro[NPCID.DesertDjinn] = true;
            player.npcTypeNoAggro[NPCID.DesertGhoul] = true;
            player.npcTypeNoAggro[NPCID.DesertGhoulCorruption] = true;
            player.npcTypeNoAggro[NPCID.DesertGhoulCrimson] = true;
            player.npcTypeNoAggro[NPCID.DesertGhoulHallow] = true;
            player.npcTypeNoAggro[NPCID.DesertLamiaDark] = true;
            player.npcTypeNoAggro[NPCID.DesertLamiaLight] = true;
            player.npcTypeNoAggro[NPCID.DesertScorpionWalk] = true;
            player.npcTypeNoAggro[NPCID.DesertScorpionWall] = true;
            player.npcTypeNoAggro[NPCID.SandElemental] = true;
            player.npcTypeNoAggro[NPCID.SandShark] = true;
            player.npcTypeNoAggro[NPCID.SandsharkCorrupt] = true;
            player.npcTypeNoAggro[NPCID.SandsharkCrimson] = true;
            player.npcTypeNoAggro[NPCID.SandsharkHallow] = true;
            player.npcTypeNoAggro[NPCID.TombCrawlerBody] = true;
            player.npcTypeNoAggro[NPCID.TombCrawlerHead] = true;
            player.npcTypeNoAggro[NPCID.TombCrawlerTail] = true;
            player.npcTypeNoAggro[NPCID.DuneSplicerBody] = true;
            player.npcTypeNoAggro[NPCID.DuneSplicerHead] = true;
            player.npcTypeNoAggro[NPCID.DuneSplicerTail] = true;
            player.npcTypeNoAggro[NPCID.Tumbleweed] = true;
            player.npcTypeNoAggro[NPCID.GraniteFlyer] = true;
            player.npcTypeNoAggro[NPCID.GraniteGolem] = true;
            player.npcTypeNoAggro[NPCID.GreekSkeleton] = true;
            player.npcTypeNoAggro[NPCID.Medusa] = true;
            player.npcTypeNoAggro[NPCID.Harpy] = true;
            player.npcTypeNoAggro[NPCID.WyvernBody] = true;
            player.npcTypeNoAggro[NPCID.WyvernBody2] = true;
            player.npcTypeNoAggro[NPCID.WyvernBody3] = true;
            player.npcTypeNoAggro[NPCID.WyvernHead] = true;
            player.npcTypeNoAggro[NPCID.WyvernLegs] = true;
            player.npcTypeNoAggro[NPCID.WyvernTail] = true;
            player.npcTypeNoAggro[NPCID.MartianProbe] = true;
            player.npcTypeNoAggro[NPCID.WindyBalloon] = true;
            player.npcTypeNoAggro[NPCID.Dandelion] = true;
            player.npcTypeNoAggro[NPCID.LadyBug] = true;
            player.npcTypeNoAggro[NPCID.GoldLadyBug] = true;
            player.npcTypeNoAggro[NPCID.LarvaeAntlion] = true;
            player.npcTypeNoAggro[NPCID.Bee] = true;
            player.npcTypeNoAggro[NPCID.CochinealBeetle] = true;
            player.npcTypeNoAggro[NPCID.Crab] = true;
            player.npcTypeNoAggro[NPCID.Crawdad] = true;
            player.npcTypeNoAggro[NPCID.Crawdad2] = true;
            player.npcTypeNoAggro[NPCID.CyanBeetle] = true;
            player.npcTypeNoAggro[NPCID.Worm] = true;
            player.npcTypeNoAggro[NPCID.GiantWormBody] = true;
            player.npcTypeNoAggro[NPCID.GiantWormHead] = true;
            player.npcTypeNoAggro[NPCID.GiantWormTail] = true;
            player.npcTypeNoAggro[NPCID.LacBeetle] = true;
            player.npcTypeNoAggro[NPCID.MushiLadybug] = true;
            player.npcTypeNoAggro[NPCID.SeaSnail] = true;
            player.npcTypeNoAggro[NPCID.TombCrawlerBody] = true;
            player.npcTypeNoAggro[NPCID.TombCrawlerHead] = true;
            player.npcTypeNoAggro[NPCID.TombCrawlerTail] = true;
            player.npcTypeNoAggro[NPCID.AnglerFish] = true;
            player.npcTypeNoAggro[NPCID.DiggerBody] = true;
            player.npcTypeNoAggro[NPCID.DiggerHead] = true;
            player.npcTypeNoAggro[NPCID.DiggerTail] = true;
            player.npcTypeNoAggro[NPCID.DuneSplicerBody] = true;
            player.npcTypeNoAggro[NPCID.DuneSplicerHead] = true;
            player.npcTypeNoAggro[NPCID.DuneSplicerTail] = true;
            player.npcTypeNoAggro[NPCID.Mimic] = true;
            player.npcTypeNoAggro[NPCID.BigMimicCorruption] = true;
            player.npcTypeNoAggro[NPCID.BigMimicCrimson] = true;
            player.npcTypeNoAggro[NPCID.BigMimicHallow] = true;
            player.npcTypeNoAggro[NPCID.BigMimicJungle] = true;
            player.npcTypeNoAggro[NPCID.IceMimic] = true;
            player.npcTypeNoAggro[NPCID.PresentMimic] = true;
            player.npcTypeNoAggro[NPCID.BlueSlime] = true;
            player.npcTypeNoAggro[NPCID.IceSlime] = true;
            player.npcTypeNoAggro[NPCID.SandSlime] = true;
            player.npcTypeNoAggro[NPCID.SpikedIceSlime] = true;
            player.npcTypeNoAggro[NPCID.SpikedJungleSlime] = true;
            player.npcTypeNoAggro[NPCID.MotherSlime] = true;
            player.npcTypeNoAggro[NPCID.LavaSlime] = true;
            player.npcTypeNoAggro[NPCID.DungeonSlime] = true;
            player.npcTypeNoAggro[NPCID.GoldenSlime] = true;
            player.npcTypeNoAggro[NPCID.UmbrellaSlime] = true;
            player.npcTypeNoAggro[NPCID.ShimmerSlime] = true;
            player.npcTypeNoAggro[NPCID.SlimeMasked] = true;
            player.npcTypeNoAggro[NPCID.SlimeRibbonGreen] = true;
            player.npcTypeNoAggro[NPCID.SlimeRibbonRed] = true;
            player.npcTypeNoAggro[NPCID.SlimeRibbonWhite] = true;
            player.npcTypeNoAggro[NPCID.SlimeRibbonYellow] = true;
            player.npcTypeNoAggro[NPCID.ToxicSludge] = true;
            player.npcTypeNoAggro[NPCID.CorruptSlime] = true;
            player.npcTypeNoAggro[NPCID.Slimer] = true;
            player.npcTypeNoAggro[NPCID.Crimslime] = true;
            player.npcTypeNoAggro[NPCID.IlluminantSlime] = true;
            player.npcTypeNoAggro[NPCID.RainbowSlime] = true;
            }
        public override void AddRecipes()
            {
            Recipe recipe = CreateRecipe();
            recipe = CreateRecipe();
            recipe.AddIngredient<RampartAccessory>(1);
            recipe.AddIngredient<NastyPattyAccessory>(1);
            recipe.AddIngredient(ItemID.TerrasparkBoots, 1);
            recipe.AddIngredient<PeaceAmongNationsAccessory>(1);
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.AddTile(TileID.AlchemyTable);
            recipe.Register();
            }
        }
    }