
using System.Collections.Generic;
using Microsoft.Xna.Framework;
using Terraria;
using Terraria.ID;
using Terraria.Localization;
using Terraria.ModLoader;
using static HendecamMod.Content.Items.Accessories.NastyPatty.NastyPattyAccessory;

namespace HendecamMod.Content.Items.Accessories.NastyPatty;

//[AutoloadEquip(EquipType.Beard)]
public class ExpiredPetFood : ModItem
{
    public override void SetDefaults()
    {
        Item.width = 16;
        Item.height = 16;
        Item.value = Item.sellPrice(silver: 8000);
        Item.rare = ItemRarityID.Orange;
        Item.accessory = true;
    }
    public override void ModifyTooltips(List<TooltipLine> tooltips)
    {
        tooltips.Add(new TooltipLine(Mod, "Tooltip#1", "Grants 3hp/s, Light, 25% Crit Chance, Double Movement Speed,"));
        tooltips.Add(new TooltipLine(Mod, "Tooltip#1", "50 Defense, Doubled Armor Penetraton, and 50% more Generic Damage"));
        tooltips.Add(new TooltipLine(Mod, "Tooltip#1", "No longer gain effects from Pets, Light Pets, Summons, Mounts,"));
        tooltips.Add(new TooltipLine(Mod, "Tooltip#1", "Minecarts, Weapon, Armor, or Accessory Buffs"));
    }
    public override void UpdateEquip(Player player)
    {
        player.GetModPlayer<NastyRegen>().NastyEffect = true;
        player.GetModPlayer<NastyLight>().NastyEffect = true;
        player.GetModPlayer<NastyCrit>().NastyEffect = true;
        player.GetModPlayer<NastyMovement>().NastyEffect = true;
        player.GetModPlayer<NastyPenetration>().NastyEffect = true;
        player.GetModPlayer<NastyDefense>().NastyEffect = true;
        player.GetModPlayer<NastyDamage>().NastyEffect = true;
        player.GetModPlayer<NastyJump>().NastyEffect = true;
        player.ClearBuff(BuffID.Flamingo);
        player.ClearBuff(BuffID.Rudolph);
        player.ClearBuff(BuffID.WitchBroom);
        player.maxMinions = 0;
        player.ClearBuff(BuffID.BabyBird);
        player.ClearBuff(BuffID.BabySlime);
        player.ClearBuff(BuffID.DeadlySphere);
        player.ClearBuff(BuffID.StormTiger);
        player.ClearBuff(BuffID.Smolstar);
        player.ClearBuff(BuffID.FlinxMinion);
        player.ClearBuff(BuffID.HornetMinion);
        player.ClearBuff(BuffID.ImpMinion);
        player.ClearBuff(BuffID.PirateMinion);
        player.ClearBuff(BuffID.Pygmies);
        player.ClearBuff(BuffID.Ravens);
        player.ClearBuff(BuffID.BatOfLight);
        player.ClearBuff(BuffID.SharknadoMinion);
        player.ClearBuff(BuffID.SpiderMinion);
        player.ClearBuff(BuffID.StardustMinion);
        player.ClearBuff(BuffID.StardustDragonMinion);
        player.ClearBuff(BuffID.EmpressBlade);
        player.ClearBuff(BuffID.TwinEyesMinion);
        player.ClearBuff(BuffID.UFOMinion);
        player.ClearBuff(BuffID.VampireFrog);
        player.ClearBuff(BuffID.BasiliskMount);
        player.ClearBuff(BuffID.BeeMount);
        player.ClearBuff(BuffID.BunnyMount);
        player.ClearBuff(BuffID.CuteFishronMount);
        player.ClearBuff(BuffID.DarkHorseMount);
        player.ClearBuff(BuffID.DarkMageBookMount);
        player.ClearBuff(BuffID.DrillMount);
        player.ClearBuff(BuffID.GolfCartMount);
        player.ClearBuff(BuffID.LavaSharkMount);
        player.ClearBuff(BuffID.MajesticHorseMount);
        player.ClearBuff(BuffID.PaintedHorseMount);
        player.ClearBuff(BuffID.PigronMount);
        player.ClearBuff(BuffID.PirateShipMount);
        player.ClearBuff(BuffID.PogoStickMount);
        player.ClearBuff(BuffID.QueenSlimeMount);
        player.ClearBuff(BuffID.SantankMount);
        player.ClearBuff(BuffID.ScutlixMount);
        player.ClearBuff(BuffID.SlimeMount);
        player.ClearBuff(BuffID.SpookyWoodMount);
        player.ClearBuff(BuffID.TurtleMount);
        player.ClearBuff(BuffID.UFOMount);
        player.ClearBuff(BuffID.UnicornMount);
        player.ClearBuff(BuffID.WallOfFleshGoatMount);
        player.ClearBuff(BuffID.WolfMount);
        player.ClearBuff(BuffID.CrimsonHeart);
        player.ClearBuff(BuffID.FairyBlue);
        player.ClearBuff(BuffID.FairyGreen);
        player.ClearBuff(BuffID.FairyRed);
        player.ClearBuff(BuffID.FairyQueenPet);
        player.ClearBuff(BuffID.PetDD2Ghost);
        player.ClearBuff(BuffID.PumpkingPet);
        player.ClearBuff(BuffID.MagicLantern);
        player.ClearBuff(BuffID.ShadowOrb);
        player.ClearBuff(BuffID.SuspiciousTentacle);
        player.ClearBuff(BuffID.GolemPet);
        player.ClearBuff(BuffID.Wisp);
        player.ClearBuff(BuffID.PetBunny);
        player.ClearBuff(BuffID.PetDD2Dragon);
        player.ClearBuff(BuffID.PetDD2Gato);
        player.ClearBuff(BuffID.PetLizard);
        player.ClearBuff(BuffID.PetParrot);
        player.ClearBuff(BuffID.PetSapling);
        player.ClearBuff(BuffID.PetSpider);
        player.ClearBuff(BuffID.PetTurtle);
        player.ClearBuff(BuffID.BerniePet);
        player.ClearBuff(BuffID.BlueChickenPet);
        player.ClearBuff(BuffID.BrainOfCthulhuPet);
        player.ClearBuff(BuffID.ChesterPet);
        player.ClearBuff(BuffID.DD2BetsyPet);
        player.ClearBuff(BuffID.DD2OgrePet);
        player.ClearBuff(BuffID.DeerclopsPet);
        player.ClearBuff(BuffID.DestroyerPet);
        player.ClearBuff(BuffID.DualSlimePet);
        player.ClearBuff(BuffID.DukeFishronPet);
        player.ClearBuff(BuffID.EaterOfWorldsPet);
        player.ClearBuff(BuffID.EverscreamPet);
        player.ClearBuff(BuffID.EyeOfCthulhuPet);
        player.ClearBuff(BuffID.GlommerPet);
        player.ClearBuff(BuffID.IceQueenPet);
        player.ClearBuff(BuffID.JunimoPet);
        player.ClearBuff(BuffID.KingSlimePet);
        player.ClearBuff(BuffID.LunaticCultistPet);
        player.ClearBuff(BuffID.MartianPet);
        player.ClearBuff(BuffID.MoonLordPet);
        player.ClearBuff(BuffID.PigPet);
        player.ClearBuff(BuffID.PlanteraPet);
        player.ClearBuff(BuffID.QueenSlimePet);
        player.ClearBuff(BuffID.SkeletronPet);
        player.ClearBuff(BuffID.SkeletronPrimePet);
        player.ClearBuff(BuffID.TwinsPet);
        player.ClearBuff(BuffID.BabyDinosaur);
        player.ClearBuff(BuffID.BabyEater);
        player.ClearBuff(BuffID.BabyGrinch);
        player.ClearBuff(BuffID.BabyHornet);
        player.ClearBuff(BuffID.BabyImp);
        player.ClearBuff(BuffID.BabyPenguin);
        player.ClearBuff(BuffID.BabyRedPanda);
        player.ClearBuff(BuffID.BabySkeletronHead);
        player.ClearBuff(BuffID.BabySnowman);
        player.ClearBuff(BuffID.BabyTruffle);
        player.ClearBuff(BuffID.BabyWerewolf);
        player.ClearBuff(BuffID.BlackCat);
        player.ClearBuff(BuffID.CavelingGardener);
        player.ClearBuff(BuffID.CompanionCube);
        player.ClearBuff(BuffID.CursedSapling);
        player.ClearBuff(BuffID.DirtiestBlock);
        player.ClearBuff(BuffID.DynamiteKitten);
        player.ClearBuff(BuffID.UpbeatStar);
        player.ClearBuff(BuffID.EyeballSpring);
        player.ClearBuff(BuffID.FennecFox);
        player.ClearBuff(BuffID.GlitteryButterfly);
        player.ClearBuff(BuffID.LilHarpy);
        player.ClearBuff(BuffID.MiniMinotaur);
        player.ClearBuff(BuffID.Plantero);
        player.ClearBuff(BuffID.Puppy);
        player.ClearBuff(BuffID.ShadowMimic);
        player.ClearBuff(BuffID.SharkPup);
        player.ClearBuff(BuffID.Spiffo);
        player.ClearBuff(BuffID.Squashling);
        player.ClearBuff(BuffID.TikiSpirit);
        player.ClearBuff(BuffID.VoltBunny);
        player.ClearBuff(BuffID.ZephyrFish);
        player.buffImmune[BuffID.TitaniumStorm] = true;
        player.buffImmune[BuffID.StardustGuardianMinion] = true;
        player.buffImmune[BuffID.ShadowDodge] = true;
        player.buffImmune[BuffID.BeetleEndurance1] = true;
        player.buffImmune[BuffID.BeetleEndurance2] = true;
        player.buffImmune[BuffID.BeetleEndurance3] = true;
        player.buffImmune[BuffID.BeetleMight1] = true;
        player.buffImmune[BuffID.BeetleMight2] = true;
        player.buffImmune[BuffID.BeetleMight3] = true;
        player.buffImmune[BuffID.SolarShield1] = true;
        player.buffImmune[BuffID.SolarShield2] = true;
        player.buffImmune[BuffID.SolarShield3] = true;
        player.buffImmune[BuffID.LeafCrystal] = true;
        player.buffImmune[BuffID.NebulaUpDmg1] = true;
        player.buffImmune[BuffID.NebulaUpDmg2] = true;
        player.buffImmune[BuffID.NebulaUpDmg3] = true;
        player.buffImmune[BuffID.NebulaUpLife1] = true;
        player.buffImmune[BuffID.NebulaUpLife2] = true;
        player.buffImmune[BuffID.NebulaUpLife3] = true;
        player.buffImmune[BuffID.NebulaUpMana1] = true;
        player.buffImmune[BuffID.NebulaUpMana2] = true;
        player.buffImmune[BuffID.NebulaUpMana3] = true;
        player.buffImmune[BuffID.BallistaPanic] = true;
        player.buffImmune[BuffID.RapidHealing] = true;
        player.buffImmune[BuffID.ParryDamageBuff] = true;
        player.buffImmune[BuffID.SoulDrain] = true;
        player.buffImmune[BuffID.HeartyMeal] = true;
        player.buffImmune[BuffID.CoolWhipPlayerBuff] = true;
        player.buffImmune[BuffID.ScytheWhipPlayerBuff] = true;
        player.buffImmune[BuffID.SwordWhipPlayerBuff] = true;
        player.buffImmune[BuffID.ThornWhipPlayerBuff] = true;
        player.buffImmune[BuffID.MinecartLeft] = true;
        player.buffImmune[BuffID.MinecartRight] = true;
        player.buffImmune[BuffID.MinecartLeftMech] = true;
        player.buffImmune[BuffID.MinecartRightMech] = true;
        player.buffImmune[BuffID.MinecartLeftWood] = true;
        player.buffImmune[BuffID.MinecartRightWood] = true;
        player.buffImmune[BuffID.AmberMinecartLeft] = true;
        player.buffImmune[BuffID.AmberMinecartRight] = true;
        player.buffImmune[BuffID.AmethystMinecartLeft] = true;
        player.buffImmune[BuffID.AmethystMinecartRight] = true;
        player.buffImmune[BuffID.BeeMinecartLeft] = true;
        player.buffImmune[BuffID.BeeMinecartRight] = true;
        player.buffImmune[BuffID.BeetleMinecartLeft] = true;
        player.buffImmune[BuffID.BeetleMinecartRight] = true;
        player.buffImmune[BuffID.CoffinMinecartLeft] = true;
        player.buffImmune[BuffID.CoffinMinecartRight] = true;
        player.buffImmune[BuffID.DesertMinecartLeft] = true;
        player.buffImmune[BuffID.DesertMinecartRight] = true;
        player.buffImmune[BuffID.DiamondMinecartLeft] = true;
        player.buffImmune[BuffID.DiamondMinecartRight] = true;
        player.buffImmune[BuffID.DiggingMoleMinecartLeft] = true;
        player.buffImmune[BuffID.DiggingMoleMinecartRight] = true;
        player.buffImmune[BuffID.EmeraldMinecartLeft] = true;
        player.buffImmune[BuffID.EmeraldMinecartRight] = true;
        player.buffImmune[BuffID.FartMinecartLeft] = true;
        player.buffImmune[BuffID.FartMinecartRight] = true;
        player.buffImmune[BuffID.FishMinecartLeft] = true;
        player.buffImmune[BuffID.FishMinecartRight] = true;
        player.buffImmune[BuffID.HellMinecartLeft] = true;
        player.buffImmune[BuffID.HellMinecartRight] = true;
        player.buffImmune[BuffID.LadybugMinecartLeft] = true;
        player.buffImmune[BuffID.LadybugMinecartRight] = true;
        player.buffImmune[BuffID.MeowmereMinecartLeft] = true;
        player.buffImmune[BuffID.MeowmereMinecartRight] = true;
        player.buffImmune[BuffID.PartyMinecartLeft] = true;
        player.buffImmune[BuffID.PartyMinecartRight] = true;
        player.buffImmune[BuffID.PigronMinecartLeft] = true;
        player.buffImmune[BuffID.PigronMinecartRight] = true;
        player.buffImmune[BuffID.PirateMinecartLeft] = true;
        player.buffImmune[BuffID.PirateMinecartRight] = true;
        player.buffImmune[BuffID.RubyMinecartLeft] = true;
        player.buffImmune[BuffID.RubyMinecartRight] = true;
        player.buffImmune[BuffID.SapphireMinecartLeft] = true;
        player.buffImmune[BuffID.SapphireMinecartRight] = true;
        player.buffImmune[BuffID.ShroomMinecartLeft] = true;
        player.buffImmune[BuffID.ShroomMinecartRight] = true;
        player.buffImmune[BuffID.SteampunkMinecartLeft] = true;
        player.buffImmune[BuffID.SteampunkMinecartRight] = true;
        player.buffImmune[BuffID.SunflowerMinecartLeft] = true;
        player.buffImmune[BuffID.SunflowerMinecartRight] = true;
        player.buffImmune[BuffID.TerraFartMinecartLeft] = true;
        player.buffImmune[BuffID.TerraFartMinecartRight] = true;
        player.buffImmune[BuffID.TopazMinecartLeft] = true;
        player.buffImmune[BuffID.TopazMinecartRight] = true;
        player.buffImmune[BuffID.Werewolf] = true;
        player.buffImmune[BuffID.Merfolk] = true;
        player.buffImmune[BuffID.IceBarrier] = true;
        player.buffImmune[BuffID.PaladinsShield] = true;
        player.buffImmune[BuffID.Panic] = true;
    }
    public override void AddRecipes()
    {
        Recipe recipe = CreateRecipe();
        recipe = CreateRecipe();
        recipe.AddIngredient<ZoologistHateLetter>(1);
        recipe.AddIngredient<MoldyCheese>(1);
        recipe.AddTile(TileID.TinkerersWorkbench);
        recipe.AddTile(TileID.Hellforge);
        recipe.Register();
    }
}